//! Cross-language roundtrip: decode transport packets generated by the real
//! sender-side RaptorQ WASM codec (scripts/encode_fixture.mjs) and verify the
//! reconstructed bytes exactly match the originals.

use std::fs;

use raptorqr_host::transfer::{
    decode_packets, decode_packets_counting_repeats, CompletedTransfer, FeedResult,
    TransferTracker,
};

/// Fixtures come from `node scripts/encode_fixture.mjs` and are **not**
/// committed, so on a fresh clone (`cargo test` in CI) these tests skip
/// instead of panicking.
fn load_fixture(name: &str) -> Option<(Vec<Vec<u8>>, Vec<u8>)> {
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");
    let packets_bytes = fs::read(format!("{dir}/{name}.packets.bin")).ok()?;
    let expected = fs::read(format!("{dir}/{name}.expected.bin")).ok()?;

    // File layout: [4-byte LE packet length][packet][packet]…
    let packet_len = u32::from_le_bytes([
        packets_bytes[0],
        packets_bytes[1],
        packets_bytes[2],
        packets_bytes[3],
    ]) as usize;
    assert!(packet_len > 12);
    let payload = &packets_bytes[4..];
    assert_eq!(
        payload.len() % packet_len,
        0,
        "packets file is not a whole number of packets"
    );
    let packets = payload
        .chunks(packet_len)
        .map(|p| p.to_vec())
        .collect::<Vec<_>>();
    Some((packets, expected))
}

fn roundtrip(name: &str, expect_filename: &str) {
    let Some((packets, expected)) = load_fixture(name) else {
        eprintln!("skipping {name}: run `node scripts/encode_fixture.mjs` to generate fixtures");
        return;
    };
    let decoded: Option<CompletedTransfer> = decode_packets(&packets);
    let transfer = decoded.unwrap_or_else(|| panic!("{name}: decode never completed"));
    assert_eq!(transfer.body, expected, "{name}: decoded bytes mismatch");
    if !transfer.is_text {
        assert_eq!(transfer.filename, expect_filename, "{name}: filename mismatch");
    }
    println!("{name}: ok ({} bytes, {} packets)", expected.len(), packets.len());
}

#[test]
fn decode_text_fixture() {
    roundtrip("text", "");
}

#[test]
fn decode_file_fixture() {
    roundtrip("file", "secret-report.bin");
}

#[test]
fn decode_multiblock_fixture() {
    roundtrip("multiblock", "big.bin");
}

/// While the sender loops, the finished transfer must stay reported as 100%
/// (not restart at 0%), and a *different* transfer afterwards must still be
/// received normally.
#[test]
fn completed_transfer_stays_complete_and_does_not_block_the_next_one() {
    let Some((packets, expected)) = load_fixture("text") else { return };
    let mut tracker = TransferTracker::new();
    let mut completions = 0;
    let mut duplicates = 0;

    for _ in 0..3 {
        for packet in &packets {
            match tracker.feed(packet) {
                FeedResult::Completed(t) => {
                    completions += 1;
                    assert_eq!(t.body, expected);
                }
                FeedResult::Duplicate => duplicates += 1,
                _ => {}
            }
        }
    }
    assert_eq!(completions, 1, "only the first pass may complete");
    assert!(duplicates > 0, "the looping passes must be skipped");

    let status = tracker.status().expect("status stays available after completion");
    assert!(status.complete.is_some(), "status must report the transfer as done");
    assert_eq!(status.progress, 1.0, "progress must not fall back to 0%");

    // A different file uses a different key and must be decoded normally.
    let Some((other_packets, other_expected)) = load_fixture("file") else { return };
    let mut second = None;
    for packet in &other_packets {
        if let FeedResult::Completed(t) = tracker.feed(packet) {
            second = Some(t);
            break;
        }
    }
    assert_eq!(second.expect("second transfer completes").body, other_expected);
}

/// The sender repeats its QR stream forever; a second full pass must be
/// reported as a duplicate instead of completing (and saving) the transfer
/// again.
#[test]
fn looping_stream_reports_duplicates() {
    let Some((packets, expected)) = load_fixture("text") else { return };
    let mut looping = packets.clone();
    looping.extend(packets.iter().cloned()); // the stream loops once more

    let (transfer, repeats) = decode_packets_counting_repeats(&looping);
    let transfer = transfer.expect("first pass did not complete");
    assert_eq!(transfer.body, expected);
    assert!(
        repeats >= 1,
        "the repeated pass produced no duplicate report (repeats={repeats})"
    );
}
